apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  volumes:
    - name: ebs-storage
      persistentVolumeClaim:   #you mention the pvc that will be attaching to your pod
        claimName: ebs-pvc   #your pvc name
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:  #this parameter provides the actual path of container where it will be mounted on your external storage.
      - mountPath: "/share/local/nginx/"  #pathway of your data storage loc
        name: ebs-storage
      ports:
       - containerPort: 80
         protocol: TCP