apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-pv
  labels:
    type: ebs
spec:
  capacity:
    storage: 10Gi  # Size of the EBS volume
  accessModes:
    - ReadWriteOnce  # Access mode for the volume
  persistentVolumeReclaimPolicy: Recycle  # Policy for the volume after release
  storageClassName: ebs-sc  # Custom storage class name
  awsElasticBlockStore:
    volumeID: aws://ap-south-1/vol-0a003ce53640c8977  # Replace with your actual EBS volume ID
    fsType: ext4  # File system type for the volume

---

