apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-pvc
spec:
  accessModes:
    - ReadWriteOnce  # Access mode for the PVC
  resources:
    requests:
      storage: 10Gi  # Must match the size of the PV
  storageClassName: ebs-sc  # Must match the storage class of the PV
